/**
 * What SignalDesk sells. Two products, and both are one table away from the
 * page a person reads, the `ServiceCard` feed an agent reads, and the `402`
 * challenge the network settles — so a price cannot appear in one place and
 * not another.
 *
 * **SignalDesk is a merchant, not part of AgentPey.** It holds its own keys,
 * runs as its own process, and imports nothing from the payment platform
 * beyond `@agentpass/core`'s neutral helpers (typed errors, ULIDs, canonical
 * JSON). That separation is the point of the pilot: if a merchant this
 * project happens to have written could reach into AgentPey's authorisation,
 * the whole demonstration would be circular.
 */
import { z } from "zod";

/** USDC on Stellar has seven decimals, so a price is quoted in ten-millionths. */
export const ASSET_DECIMALS = 7;

export const SIGNALDESK_SLUG = "signaldesk";

export type ProductId = (typeof PRODUCTS)[number]["id"];

export interface SignalDeskProduct {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  /** Decimal USDC, the form a human and a `ServiceCard` both read. */
  readonly price: string;
  /** The same price in atomic units, the form x402 settles. Derived, never typed twice. */
  readonly priceAtomic: string;
  /** The paid route, with `{name}` placeholders — what `getX402ServiceRoute` reads. */
  readonly routeTemplate: string;
  readonly path: string;
  readonly input: readonly { readonly name: string; readonly type: string; readonly required: boolean }[];
}

/** `0.25` → `2500000`. String arithmetic end to end: no float ever touches a price. */
export function toAtomic(decimal: string): string {
  const [whole = "0", fraction = ""] = decimal.split(".");
  const padded = (fraction + "0".repeat(ASSET_DECIMALS)).slice(0, ASSET_DECIMALS);
  return `${BigInt(whole) * 10n ** BigInt(ASSET_DECIMALS) + BigInt(padded || "0")}`;
}

function product(
  input: Omit<SignalDeskProduct, "priceAtomic" | "routeTemplate"> & { readonly query: string },
): SignalDeskProduct {
  return {
    id: input.id,
    name: input.name,
    description: input.description,
    price: input.price,
    priceAtomic: toAtomic(input.price),
    path: input.path,
    routeTemplate: `${input.path}${input.query}`,
    input: input.input,
  };
}

/**
 * The market brief is **synthetic data generated by SignalDesk**, and the
 * artefact says so in its first line rather than in grey type at the bottom.
 * It is not, and does not imitate, any real market data product — not the
 * name, not the look, not the content. That constraint comes from the brief
 * and it is the right one well beyond this pilot.
 *
 * The AI credits are an **entitlement, not an asset**: a row in SignalDesk's
 * own database tied to one holder — a Stellar address, or the opaque reference
 * a platform knows its user by (see {@link accountSchema}) — with no transfer
 * operation anywhere in this service. That is a structural choice, not a policy one. A
 * transferable "credit" would be an issuance, and issuance is on the far side
 * of the line this project keeps closed.
 */
export const PRODUCTS = [
  product({
    id: "signaldesk:market-brief-xlm-usdc",
    name: "Informe de mercado XLM/USDC",
    description:
      "Un informe de demostracion del par XLM/USDC, generado con datos sinteticos propios de SignalDesk. No es asesoramiento ni datos de mercado reales.",
    price: "0.25",
    path: "/api/x402/market-brief",
    query: "?pair={pair}",
    input: [{ name: "pair", type: "string", required: true }],
  }),
  product({
    id: "signaldesk:ai-credits-1000",
    name: "1000 creditos de IA",
    description:
      "Mil creditos de producto acreditados a quien compra: una direccion Stellar o la referencia opaca con que su plataforma lo identifica. No es un token, no es transferible, y solo sirve dentro de SignalDesk.",
    price: "0.10",
    path: "/api/x402/ai-credits",
    query: "?account={account}",
    input: [{ name: "account", type: "string", required: true }],
  }),
] as const satisfies readonly SignalDeskProduct[];

/** The one pair the brief knows how to write about. Anything else is refused, never improvised. */
export const SUPPORTED_PAIR = "XLM/USDC";

/** How many credits one purchase of the credits product grants. */
export const CREDITS_PER_PURCHASE = 1000;

/** Artefacts are kept for this long, and the catalogue page says so. */
export const ARTIFACT_RETENTION_DAYS = 90;

/**
 * Who a credits balance belongs to: a Stellar classic account, or an opaque
 * reference a platform knows its user by — `<prefix>_<ulid>`, like RealOps'
 * `rop_…`.
 *
 * The second shape exists because T85 found the credits product unbuyable
 * from the pilot's own platform: RealOps sends the reference AgentPey knows the
 * person by (`C-98`), deliberately never anything personal, and this schema
 * refused it with a `400`. Accepting a wallet address instead would have handed
 * SignalDesk a stable identifier of the person's wallet, which is exactly what
 * `C-98` keeps from it.
 *
 * Still closed, on purpose: a ULID has no `@`, no spaces and no free text, so an
 * email, a phone number or a name cannot pass as a reference.
 */
export const accountSchema = z.union([
  z.string().regex(/^G[A-Z2-7]{55}$/, "expected a Stellar classic account"),
  z.string().regex(/^[a-z][a-z0-9]{1,15}_[0-9A-HJKMNP-TV-Z]{26}$/, "expected an opaque reference like rop_<ulid>"),
]);

export const pairSchema = z.literal(SUPPORTED_PAIR);

/** The product served at a path, or `undefined` for a path that sells nothing. */
export function productForPath(path: string): SignalDeskProduct | undefined {
  return PRODUCTS.find((candidate) => candidate.path === path);
}

export function productById(id: string): SignalDeskProduct | undefined {
  return PRODUCTS.find((candidate) => candidate.id === id);
}
